apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels: {{ include "common.labels" . | nindent 4}}
  name: {{.Chart.Name}}
  namespace: default
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels: {{ include "common.labels" . | nindent 6}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels: {{ include "common.labels" . | nindent 8}}
    spec:
      containers:
      - image: {{.Values.image.repository}}/{{.Values.image.name}}:{{.Values.image.tag | default .Chart.AppVersion}}
        imagePullPolicy: IfNotPresent
        name: {{.Values.image.name}}
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health/readiness
            port: {{.Values.service.port}}
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health/liveness
            port: {{.Values.service.port}}
      restartPolicy: Always

